# Generated by Django 3.2.7 on 2021-10-13 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sizeRank', models.IntegerField()),
                ('country', models.TextField(max_length=50)),
                ('state', models.TextField(max_length=50)),
                ('city', models.TextField(max_length=50)),
                ('rent1YearAvg', models.IntegerField()),
                ('rent5YearAvg', models.IntegerField()),
                ('value1YearAvg', models.IntegerField()),
                ('value5YearAvg', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
