# Generated by Django 3.2.8 on 2021-10-06 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HousingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.TextField(max_length=50)),
                ('state', models.TextField(max_length=50)),
                ('city', models.TextField(max_length=50)),
                ('rent', models.IntegerField(max_length=50)),
                ('price', models.IntegerField(max_length=50)),
                ('ratio', models.IntegerField(max_length=50)),
            ],
        ),
    ]
