# Generated by Django 3.2.8 on 2021-10-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyCapApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='housingdata',
            name='sizeRank',
            field=models.IntegerField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='housingdata',
            name='ratio',
            field=models.FloatField(max_length=50),
        ),
    ]
