# Generated by Django 3.2.8 on 2021-10-08 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyCapApp', '0002_auto_20211008_1441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='housingdata',
            old_name='price',
            new_name='rent1YearAvg',
        ),
        migrations.RenameField(
            model_name='housingdata',
            old_name='rent',
            new_name='rent5YearAvg',
        ),
        migrations.RemoveField(
            model_name='housingdata',
            name='ratio',
        ),
        migrations.AddField(
            model_name='housingdata',
            name='value1YearAvg',
            field=models.IntegerField(null=True, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='housingdata',
            name='value5YearAvg',
            field=models.IntegerField(null=True, max_length=50),
            preserve_default=False,
        ),
    ]
