# Generated by Django 3.2.7 on 2021-10-11 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyCapApp', '0004_auto_20211011_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housingdata',
            name='sizeRank',
            field=models.IntegerField(),
        ),
    ]
