# Generated by Django 3.2.7 on 2021-10-12 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyCapApp', '0005_alter_housingdata_sizerank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housingdata',
            name='user',
        ),
    ]
