# Generated by Django 3.2.7 on 2021-10-13 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyCapApp', '0007_datacart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataCart',
        ),
    ]
